openapi: 3.0.0
info:
  title: Simple API
  description: A simple API to demonstrate Swagger in JSON format.
  version: 1.0.0

servers:
  - url: https://65.108.50.91/zaaroz_new/public/api/za1
    description: Local server
  - url: https://uat.zaaroz.in/zaarsec/public/api/za1/
    description: UAT server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses: {}
  schemas: {}

paths:
  /settings:
    post:
      summary: Retrieve Zaaroz admin panel settings
      tags: [Settings]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  setting: 
                    type: string
                    example: "Value"
      operationId: postSettings
      description: This API is used to retrieve Zaaroz admin panel setting details.

  /buyer_signin:
    post:
      summary: Buyer Sign-In
      tags: [Buyer]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
      operationId: postBuyerSignin
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                device_token:
                  type: string
                device_type:
                  type: string
                mobile_no:
                  type: string
                unique_id:
                  type: string
              example:
                device_token: 'eevnxf2MT5mO26OQvyCbjD:APA91bHTmppjl8ZBkZOOrf2ZN7NtD-Kypun3gjveTAARSSguG7a3-jGFKVPFczmqSYyuQV-tt20GRD30vZn0OBT9gHKEvZNDsjDlyBVEVcmXas9NbBMeOfQ'
                device_type: A
                mobile_no: '7826907370'
                unique_id: 838e343d-80a2-4988-bc97-0f9c8256d223

  /buyer_details:
    post:
      summary: Retrieve Buyer Details
      tags: [Buyer]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  details:
                    type: string
      operationId: postBuyerDetails
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                restaurant_id:
                  type: string
              example:
                restaurant_id: '1'
      parameters: []
      security:
        - bearerAuth: []

security:
  - bearerAuth: []
