openapi: 3.0.0
info:
  title: Simple API
  description: A simple API to demonstrate Swagger in JSON format.
  version: 1.0.0
servers:
- url: http://65.108.50.91/zaaroz_new/public/api/za1
  description: Local server
security:
- bearerAuth: []
paths:
  /buyer_details:
    post:
      tags: []
      summary: Your POST endpoint
      operationId: post-buyer_details
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/buyer_details_body'
      responses: {}
      security:
      - bearerAuth: []
components:
  schemas:
    buyer_details_body:
      type: object
      properties:
        restaurant_id:
          type: string
      x-examples:
        Example 1:
          restaurant_id: "1"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
